### ISSUE TITLE
how can I patch `nim` instead of using bundled version (old: 0.18) you provide?

### ISSUE THREAD

**Issue by timotheecour** [Feneric/nim-wasm-helpers#1]
the nim version you provide is old:
```nim
vagrant@bodhi64 /v/Samples> nim --version
Nim Compiler Version 0.18.0 [Linux: amd64]
```

furthermore, I'd like to use up to date nim (or even own fork), how would I patch nim so it'd work the same as in instructions given in https://www.spiria.com/en/blog/web-applications/webassembly-nim ?

**Comment by Feneric** [comment]
Yeah, there is actually quite a bit in there that needs to get updated, starting with the OS version itself. I had started to build a new Vagrant box the other day but got sidetracked. Hopefully I'll be able to build the new one and use it for some updates here in the near future.

**Comment by timotheecour** [comment]
i think the approach I tried here https://github.com/Feneric/nim-wasm-helpers/issues/2#issuecomment-435751256 is good enough for a fix, closing

**Comment by Feneric** [comment]
I got the Vagrant box updated last night. I'm starting to go through and update everything else on top of the OS now.
